WATCHLIST = [
    "BTC/USDT",
    "ETH/USDT",
    "SOL/USDT",
    "XRP/USDT",
    "LINK/USDT",
    "SUI/USDT",
    "DOGE/USDT",
    "ADA/USDT",
    "AVAX/USDT",
    "BNB/USDT",
]

EXCHANGE_IDS = ["kucoin", "okx", "bybit", "binance"]
TIMEFRAME = "4h"
OHLCV_LIMIT = 500

SWING_LENGTH = 10
ATR_PERIOD = 50
BOX_WIDTH = 2.5

MAX_DISTANCE_PCT = 1.0
REARM_FACTOR = 1.25
SCAN_SLEEP = 300
ALERT_COOLDOWN_SECONDS = 4 * 60 * 60

PRINT_SCAN_SUMMARY = True
PRINT_ALERTS_TO_CONSOLE = True

TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
DISCORD_WEBHOOK_URL = ""
