WATCHLIST = [
    "BTCUSD",
    "ETHUSD",
    "PAXGUSD",
    "SOLUSD",
    "XRPUSD",
    "SLVONUSD",
    "DOGEUSD",
    "ZECUSD",
    "HYPEUSD",
    "RIVERUSD",
    "LINKUSD",
    "LTCUSD",
    "AVAXUSD",
    "QQQXUSD",
    "TSLAXUSD",
    "SUIUSD",
    "METAXUSD",
    "SPYXUSD",
    "AMZNXUSD",
    "NVDAXUSD",
    "AAPLXUSD",
    "XMRUSD",
    "CRCLXUSD",
    "GOOGLXUSD",
    "COINXUSD",
    "BNBUSD",
    "ADAUSD",
    "DOTUSD",
    "BCHUSD",
    "NEARUSD",
    "AAVEUSD",
    "UNIUSD",
    "APTUSD",
    "ARBUSD",
    "OPUSD",
    "INJUSD",
    "TIAUSD",
    "SEIUSD",
    "FILUSD",
    "ETCUSD",
    "TRIA/USDT",
    "VIRTUAL/USDT",
    "ONDOUSD",
    "FET/USDT",
    "PUMPUSD",
    "T/USDT",
    "1000BONKUSD",
    "LDO/USDT",
    "CRV/USDT",
    "XLM/USDT",
    "MUSD",
    "GRAMUSD",
    "XPLUSD",
    "RIF/USDT",
    "LABUSD",
    "DODO/USDT",
    "DEXE/USDT",
    "AIOTUSD",
    "VELVET/USDT",
    "1000SHIBUSD",
    "FARTCOIN/USDT",
    "SXT/USDT",
    "THE/USDT",
    "BILLUSD",
    "SYN/USDT",
    "WLD/USDT",
    "1000PEPEUSD",
    "LIT/USDT",
    "ALLO/USDT",
    "EVAAUSD",
    "ENA/USDT",
    "TAO/USDT",
    "SOXLBUSD",
    "SNDKBUSD",
    "MUBUSD",
    "SPCXXUSD",
    "EWYBUSD",
    "DRAMBUSD",
    "CBRSBUSD",
    "INTCBUSD",
    "MSTRBUSD",
]

DELTA_API_BASE_URL = "https://api.india.delta.exchange"
PRIMARY_EXCHANGE_ID = "binance"
EXCHANGE_IDS = ["binance", "kucoin", "okx", "bybit"]
TIMEFRAME = "4h"
OHLCV_LIMIT = 500

SWING_LENGTH = 10
ATR_PERIOD = 50
BOX_WIDTH = 2.5

MAX_DISTANCE_PCT = 1.5
REARM_FACTOR = 1.25
SCAN_SLEEP = 300
SCAN_WORKERS = 8
ALERT_COOLDOWN_SECONDS = 4 * 60 * 60
ALERT_RANGE_FILTER_SIGNALS = True
SIGNAL_ALERT_COOLDOWN_SECONDS = 4 * 60 * 60

PRINT_SCAN_SUMMARY = True
PRINT_ALERTS_TO_CONSOLE = True

TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
DISCORD_WEBHOOK_URL = ""
DISCORD_STATUS_WEBHOOK_URL = ""
